from typing import List
import random

from django.contrib.auth.models import User

from task_list.models import Task


class TestSet:

    def __init__(self):
        self.clear_all_objects()

    def clear_all_objects(self) -> None:
        User.objects.filter(is_staff=False, is_superuser=False).delete()
        Task.objects.all().delete()

    def generate_test_set(self):
        users = self.create_all_users()
        self.create_all_tasks(users)

    def create_all_users(self) -> List[User]:
        users = list()
        users.append(self._create_user('alice', 'alice'))
        users.append(self._create_user('bob', 'bob'))
        users.append(self._create_user('eve', 'eve'))
        return users

    def _create_user(self, username: str, password: str) -> User:
        user = User.objects.create_user(username, password=password)
        user.save()
        return user

    def create_all_tasks(self, users: List[User]) -> None:
        for i in range(20):
            owner = random.choice(users)
            name = 'Task autogenerated for user '+str(owner)
            is_done = random.choice([True, False])
            self._create_task(name, owner, is_done)

    def _create_task(self, name: str, owner: User, is_done: bool)->None:
        Task(name=name, owner=owner, is_done=is_done).save()


if __name__ == '__main__':
    testset = TestSet()
    testset.generate_test_set()

