# Generated by Django 2.1.2 on 2018-10-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='is_done',
        ),
    ]
